import { Montserrat } from 'next/font/google';
import "../globals.css";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Choose the weights you need
  variable: '--font-montserrat', // Optional: for Tailwind custom font
});

export const metadata = {
  title: "CoreFocus",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
      <div>
        <Navbar /> 
        {children}
        <Footer />
      </div>
  );
}
