import { Montserrat } from 'next/font/google';
import "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Choose the weights you need
  variable: '--font-montserrat', // Optional: for Tailwind custom font
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="en" className={`${montserrat.variable}`}>
      <body>
        <Navbar /> 
        {children}
        <Footer />
      </body>
    </html>
  );
}
